module.exports = {
  fishTypes: {
    Fish_1_: { id: 1, name: 'Nose Shark', rarity: 'Common', count: 0 },
    Fish_2_: { id: 2, name: 'Horned Pike', rarity: 'Common', count: 0 },
    Fish_3_: { id: 3, name: 'Sea Carp', rarity: 'Common', count: 0 },
    Fish_4_: { id: 4, name: 'Coral Bird', rarity: 'Common', count: 0 },
    Fish_5_: { id: 5, name: 'Sidewinder', rarity: 'Common', count: 0 },
    Fish_6_: { id: 6, name: 'Grumpyfin', rarity: 'Common', count: 0 },
    Fish_7_: { id: 7, name: 'Dungeness Crab', rarity: 'Common', count: 0 },
    Fish_8_: { id: 8, name: 'Smithfish', rarity: 'Common', count: 0 },
    Fish_9_: { id: 9, name: 'Littlefin', rarity: 'Common', count: 0 },
    Fish_10_: { id: 10, name: 'Arrow Fish', rarity: 'Common', count: 0 },
    Fish_11_: { id: 11, name: 'Trakanian Catfish', rarity: 'Rare', count: 0 },
    Fish_12_: { id: 12, name: 'Bahamut', rarity: 'Rare', count: 0 },
    Fish_13_: { id: 13, name: 'Reefer', rarity: 'Rare', count: 0 },
    Fish_14_: { id: 14, name: 'Gemfin', rarity: 'Rare', count: 0 },
    Fish_15_: { id: 15, name: 'The Lord', rarity: 'Rare', count: 0 },
    Fish_16_: { id: 16, name: 'Daggernose', rarity: 'Epic', count: 0 },
    Fish_17_: { id: 17, name: 'Runed Octopus', rarity: 'Epic', count: 0 },
    Fish_18_: { id: 18, name: 'Trakan Bay Shark', rarity: 'Epic', count: 0 },
    Fish_19_: { id: 19, name: 'Halibhun Lobster', rarity: 'Epic', count: 0 },
    Fish_20_: { id: 20, name: 'Majestic Seahorse', rarity: 'Epic', count: 0 },
    Fish_21_: { id: 21, name: 'Anglerfish', rarity: 'Legendary', count: 0 },
    Fish_22_: { id: 22, name: 'Devourer', rarity: 'Legendary', count: 0 },
    Fish_23_: { id: 23, name: 'Spike Ray', rarity: 'Legendary', count: 0 },
    Fish_24_: { id: 24, name: 'Nightcrawler', rarity: 'Legendary', count: 0 },
  },
  itemIds: {
    'Common Fish': {
      poolId: 1,
      memberId: 0,
      contractAddress: '',
      tokenUri: 'ipfs://QmPfvYzGUjkGydD8fWrTXkb9DcKi3khkikatao5Xme837J/commonFish.json',
      name: 'Common Fish',
    }, //'COMMON',
    'Rare Fish': {
      poolId: 2,
      memberId: 0,
      contractAddress: '',
      tokenUri: 'ipfs://QmPfvYzGUjkGydD8fWrTXkb9DcKi3khkikatao5Xme837J/rareFish.json',
      name: 'Rare Fish',
    }, //'RARE',
    'Epic Fish': {
      poolId: 3,
      memberId: 0,
      contractAddress: '',
      tokenUri: 'ipfs://QmPfvYzGUjkGydD8fWrTXkb9DcKi3khkikatao5Xme837J/epicFish.json',
      name: 'Epic Fish',
    }, //'EPIC',
    'Legendary Fish': {
      poolId: 4,
      memberId: 0,
      contractAddress: '',
      tokenUri: 'ipfs://QmPfvYzGUjkGydD8fWrTXkb9DcKi3khkikatao5Xme837J/legendaryFish.json',
      name: 'Legendary Fish',
    }, //'LEGENDARY',
    'Common Triumph': {
      poolId: 1,
      memberId: 0,
      contractAddress: '0xCD70e6cc957d802Def6de66482f04C76c99E4E61',
      tokenUri: 'ipfs://QmNq8puefqR1tpEmKeafJMgGKsCwGWEUDZVmVmcXs3tcfs',
      name: 'Common Triumph',
    }, //'COMMON',
    'Rare Triumph': {
      poolId: 2,
      memberId: 0,
      contractAddress: '0xCD70e6cc957d802Def6de66482f04C76c99E4E61',
      tokenUri: 'ipfs://QmcZk4udFs3youLppijqQ7cAmYRNzCC55NDhqvcsc3UW7g',
      name: 'Rare Triumph',
    }, //'RARE',
    'Epic Triumph': {
      poolId: 3,
      memberId: 0,
      contractAddress: '0xCD70e6cc957d802Def6de66482f04C76c99E4E61',
      tokenUri: 'ipfs://QmShxqtstA14BzGwuE8ywv2kDUM91foNYhRdxdhce5XAcS',
      name: 'Epic Triumph',
    }, //'EPIC',
    'Legendary Triumph': {
      poolId: 4,
      memberId: 0,
      contractAddress: '0xCD70e6cc957d802Def6de66482f04C76c99E4E61',
      tokenUri: 'ipfs://QmbSFPgaN6sAc9BdTGgcMGzNzY1UbYMthKdzsVJwAGtDdn',
      name: 'Legendary Triumph',
    }, //'LEGENDARY',
  }
} 
